-- Cache genérico dos recursos extraídos do IMDB (filmes, pessoas, ...).
-- Estratégia: documento JSON único por (tipo, chave, locale); fetched_at controla o TTL.
CREATE TABLE imdb_cache (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo       VARCHAR(20)  NOT NULL,
    chave      VARCHAR(20)  NOT NULL,
    locale     VARCHAR(20)  NOT NULL,
    payload    TEXT         NOT NULL,
    fetched_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_imdb_cache UNIQUE (tipo, chave, locale)
);
